[package]
name = "transfer-role-features-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.transfer-role-features]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.5.2"
path = "../../../../../dharitri-wasm-debug"
