[package]
name = "moax-dct-swap-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.moax-dct-swap]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.5.2"
path = "../../../../dharitri-wasm-debug"
