[package]
name = "kitty-ownership-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.kitty-ownership]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.5.2"
path = "../../../../../dharitri-wasm-debug"
