[package]
name = "payable-features-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@dharitri.com>"]
edition = "2018"
publish = false

[dependencies.payable-features]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.5.2"
path = "../../../../dharitri-wasm-debug"
